docs_dir: .

# Project information
site_name: OpenSR test
site_url: https://github.com/JulioContrerasH/opensr-test
site_author: Open SR test Contributors
site_description: A comprehensive benchmark for real-world Sentinel-2 imagery super-resolution


# Repository
repo_url: https://github.com/JulioContrerasH/opensr-test
repo_name: OpenSR test
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: docs/images/logo.png
  favicon: resources/ms_icon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide

# Page tree
nav:
  - Home:
    - README.md
    - Contributing: docs/CONTRIBUTING.md
    - Code of Conduct: docs/Code_of_Conduct.md
    - Changelog: docs/CHANGELOG.md
    - License: docs/LICENSE.md
  - Properties:
    - docs/Properties/main.md
  - API:
    - Model parameters: docs/API/model_parameters.md
    - Setup method: docs/API/setup_method.md
    - Compute method: docs/API/compute_method.md
    - Summary method: docs/API/summary_method.md
    - Results attributes: docs/API/results_attributes.md
  - Dataset:
    - Home: docs/Dataset/main.md
    - NAIP: docs/Dataset/NAIP.md
    - SPOT: docs/Dataset/SPOT.md
    - Venµs: docs/Dataset/Venµs.md
  - Metrics:
    - Consistency metrics: docs/Metrics/consistency.md
    - Distance metrics: docs/Metrics/distance.md
    - Correctness metrics: docs/Metrics/correctness.md    
  - Examples:
    - PyTorch models: docs/Examples/pytorch_models.md
    - Tensorflow models: docs/Examples/tensorflow_models.md
    - Diffuser models: docs/Examples/diffuser_models.md
    - Multi-image SR model: docs/Examples/multi_image_sr_model.md
    - Create correctness animation: docs/Examples/create_correctness_animation.md
  - Benchmarks:
    - docs/benchmarks.md


# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js